apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-cpu-request: 10m
        config.linkerd.io/proxy-memory-request: 10Mi
        config.linkerd.io/proxy-cpu-limit: 30m
        config.linkerd.io/proxy-memory-limit: 30Mi
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: web
          image: busybox
          command:
            - /app/node_modules/.bin/nuxt
            - start
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 120Mi
          env:
            - name: NUXT_HOST
              value: 0.0.0.0
            - name: NUXT_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: http

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: web
